# Generated by Django 3.2 on 2023-10-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdata',
            name='recorded_voice',
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='recorded_audio',
            field=models.FileField(blank=True, null=True, upload_to='biometric_data/audios/'),
        ),
    ]
